; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; PlatformIO Project Configuration File
; ESPSomfy-RTS v2.5.3

[platformio]
default_envs = esp32dev ; L'environnement par défaut quand tu compiles sur ton VS Code

; --- CONFIGURATION COMMUNE A TOUTES LES CARTES ---
[env]
platform = espressif32@6.8.1
framework = arduino
lib_deps =
    bblanchon/ArduinoJson @ 6.21.5
    knolleary/PubSubClient @ 2.8.0
    lsatan/SmartRC-CC1101-Driver-Lib @ 2.5.7
    esp32async/ESPAsyncWebServer @ 3.6.0
    esp32async/AsyncTCP @ 3.3.2
    links2004/WebSockets @ 2.4.1

extra_scripts = 
    pre:prepare_assets.py
board_build.filesystem = littlefs
monitor_speed = 115200
board_build.f_flash = 80000000L
board_build.flash_mode = qio
build_flags = 
    -D CORE_DEBUG_LEVEL=0



; --- DEFINITION DES VARIANTES DE CARTES ---



[env:esp32dev]
board = esp32dev
board_build.partitions = default.csv

[env:esp32wrover]
board = esp-wrover-kit
board_build.partitions = default.csv

[env:esp32c3]
board = esp32-c3-devkitm-1
board_build.partitions = default.csv

[env:esp32s2]
board = esp32-s2-saola-1
board_build.partitions = default.csv

[env:esp32s3]
board = esp32-s3-devkitc-1
board_build.partitions = default.csv
