[platformio]
default_envs = esp32dev


[env]
platform = espressif32@6.8.1
framework = arduino
lib_deps =
    bblanchon/ArduinoJson @ 6.21.5
    knolleary/PubSubClient @ 2.8.0
    lsatan/SmartRC-CC1101-Driver-Lib @ 2.5.7
    esp32async/ESPAsyncWebServer @ 3.6.0
    esp32async/AsyncTCP @ 3.3.2
    links2004/WebSockets @ 2.4.1

extra_scripts = 
    pre:minify_data.py
board_build.filesystem = littlefs
monitor_speed = 115200
board_build.f_flash = 80000000L
board_build.flash_mode = qio
build_flags = 
    -D CORE_DEBUG_LEVEL=0


[env:esp32dev]
board = esp32dev
board_build.partitions = default.csv

[env:esp32wrover]
board = esp-wrover-kit
board_build.partitions = default.csv
build_flags =
    ${env.build_flags}
    -D BOARD_HAS_PSRAM

[env:esp32c3]
board = esp32-c3-devkitm-1
board_build.partitions = default.csv

[env:esp32s2]
board = esp32-s2-saola-1
board_build.partitions = default.csv

[env:esp32s3]
board = esp32-s3-devkitc-1
board_build.partitions = default.csv
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_CDC_ON_BOOT=1
