name: ESPSomfy-RTS CI

on: [push, pull_request]

jobs:
  # JOB 1 : Génère le LittleFS unique comme avant
  littlefs:
    name: LittleFS
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PlatformIO
        run: pip install platformio

      # Génération via l'environnement par défaut esp32dev
      - name: Build LittleFS image
        run: pio run -e esp32dev -t buildfs

      - name: Rename LittleFS to Standard Name
        run: cp .pio/build/esp32dev/littlefs.bin SomfyController.littlefs.bin

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: LittleFS
          path: SomfyController.littlefs.bin
          retention-days: 5

  # JOB 2 : Matrice des cartes qui dépend du job littlefs
  arduino:
    name: ${{ matrix.name }}
    needs: [littlefs]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - env: esp32dev
            name: ESP32
            chip: ESP32
            addr_bootloader: "0x1000"
          - env: esp32wrover
            name: ESP32-Wrover
            chip: ESP32
            addr_bootloader: "0x1000"
          - env: esp32c3
            name: ESP32C3
            chip: ESP32-C3
            addr_bootloader: "0x0"
          - env: esp32s2
            name: ESP32S2
            chip: ESP32-S2
            addr_bootloader: "0x1000"
          - env: esp32s3
            name: ESP32S3
            chip: ESP32-S3
            addr_bootloader: "0x0"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get LittleFS
        uses: actions/download-artifact@v4
        with:
          name: LittleFS

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PlatformIO and esptool
        run: pip install platformio esptool

      - name: Build firmware
        run: pio run -e ${{ matrix.env }}

      - name: ${{ matrix.name }} Image
        run: |
          python -m esptool --chip ${{ matrix.chip }} \
            merge-bin -o .pio/build/${{ matrix.env }}/SomfyController.onboard.bin \
            ${{ matrix.addr_bootloader }} .pio/build/${{ matrix.env }}/bootloader.bin \
            0x8000 .pio/build/${{ matrix.env }}/partitions.bin \
            0x10000 .pio/build/${{ matrix.env }}/firmware.bin \
            0x290000 SomfyController.littlefs.bin

      - name: Upload ${{ matrix.name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: |
            .pio/build/${{ matrix.env }}/firmware.bin
            .pio/build/${{ matrix.env }}/bootloader.bin
            .pio/build/${{ matrix.env }}/partitions.bin
            .pio/build/${{ matrix.env }}/SomfyController.onboard.bin
          retention-days: 5
